#export IOTEDGE_IOTHUBHOSTNAME="IOTEDGE"

#export IOTHUB_DEVICE_SECURITY_TYPE="DPS"
#export IOTHUB_DEVICE_DPS_ENDPOINT="global.azure-devices-provisioning.net"
#export IOTHUB_DEVICE_DPS_ID_SCOPE=""
#export IOTHUB_DEVICE_DPS_DEVICE_ID=""
#export IOTHUB_DEVICE_DPS_DEVICE_KEY=""

export IOTHUB_DEVICE_SECURITY_TYPE="connectionString"
export IOTHUB_DEVICE_CONNECTION_STRING="HostName;DeviceId=;SharedAccessKey="